import Head from "next/head";

import { GetStaticProps, InferGetStaticPropsType } from "next";

import { recipesData } from "../../../queries/recipes";
import { categoryFilteredData } from "../../../queries/recipes";
export const getStaticProps: GetStaticProps = async (context) => {
  const pageProps = await recipesData(context);
  const relatedRecipesProps = await categoryFilteredData(context);

  return {
    props: {
      page: pageProps?.data || null,
      params: context.params,
      relatedRecipes: relatedRecipesProps?.data || null,
    },
  };
};

export async function getStaticPaths() {
  return {
    paths: ["/recipes/categories/[slug]"],
    fallback: true,
  };
}

export const Page = (data: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log("data... check if we have related recipes", data);
  let slug = data?.params?.slug;
  return (
    <>
      <Head>
        <title>{"test"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {slug ? (
        <div>
          <h1>Recipes Based on {slug}</h1>
          {data?.relatedRecipes?.map((recipe: any) => {
            return <h1>{recipe?.title}</h1>;
          })}
        </div>
      ) : null}
      ;
    </>
  );
};
export default Page;
