import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { categoryData } from "../../queries/categories";
import { categoryFilteredData } from "../../queries/recipes";
import { SanityImage } from "../../components/image/SanityImage";

import { RecipeCard } from "../../components/recipeCard";
// getStaticProps
export const getStaticProps: GetStaticProps = async (context) => {
  const pageProps = await categoryData(context);
  const relatedRecipesProps = await categoryFilteredData(context);
  return {
    props: {
      page: pageProps?.data || null,
      relatedRecipes: relatedRecipesProps?.data || null,
    },
  };
};

export async function getStaticPaths() {
  return {
    paths: ["/categories/[slug]"],
    fallback: true,
  };
}

export const Page = (data: InferGetStaticPropsType<typeof getStaticProps>) => {
  let categoryObject = data?.page?.[0];

  return (
    <>
      <Head>
        <title>Category - {categoryObject?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className={
            "container bg-white mx-auto m-10 p-10 rounded overflow-hidden shadow-xl mt-4 flex-none text-center"
          }
        >
          <SanityImage
            image={categoryObject?.image}
            alt={categoryObject?.alt}
            width={400}
          />
          <h1>{categoryObject?.title}</h1>
          <p className="text-gray-700 text-lg">{categoryObject?.description}</p>
          {/* Testing */}
          {data?.relatedRecipes ? (
            <div className="container bg-white mx-auto m-10 p-10 rounded overflow-hidden shadow-xl mt-4 flex-none text-center">
              {/* <p>Recipes Based on {categoryObject?.title}</p> */}
              <div className="grid gap-10 grid-cols-4">
                {data?.relatedRecipes?.map((recipe: any) => {
                  return <RecipeCard recipe={recipe} post={recipe} />;
                })}
              </div>
            </div>
          ) : null}
        </div>
      </main>
    </>
  );
};

export default Page;
