import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";

import { getCategoryPaths, recipeData } from "../../queries/recipes";

interface ISlug {
  slug: string;
}

// getStaticPaths
export const getStaticPaths: GetStaticPaths = async () => {
  const categoryPaths: ISlug[] = await getCategoryPaths();
  const paths = categoryPaths?.map(({ slug }) => ({
    params: { slug: slug },
  }));

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async (context) => {
  const pageProps = await recipeData(context);

  return {
    props: {
      page: pageProps?.data || null,
    },
  };
};

export const Page = (data: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log("data", data);

  let test = "name of recipe slug";
  return (
    <>
      <Head>
        <title>{test}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <main className={styles.main}>
          <div>
            <Image
              src="/vercel.svg"
              width="600"
              height="1200"
              alt="Recipe Image"
            />
            <p>Servings: 4</p>
            <p>Creator: little circle that links to author</p>
            <br></br>
            <label>Recipe Description:</label>
            <p>
              Lorem ipsum dolor sit amet. Ut doloribus voluptas ab numquam
              tempora et sint asperiores nam omnis excepturi et nobis deleniti
              qui accusamus cupiditate ad vitae exercitationem. Ut dolorem sint
              ab nihil modi qui quibusdam dicta rem minima molestiae est cumque
              dolorem ut aliquid odit a repellendus minima. 33 excepturi velit
              id placeat accusamus est corrupti autem eum voluptate distinctio
              ut nobis similique et esse magni ut omnis Quis? Qui dolor quidem
              in inventore iure et itaque facilis ea quasi provident. Eum iusto
              quidem sit molestias veniam non velit quasi aut commodi deleniti
              ut accusamus quae. Qui ullam voluptate ut inventore eaque ea
              veritatis pariatur? Et deleniti voluptatum ut voluptate modi aut
              voluptatibus voluptas ut rerum libero. Sit aliquid voluptatem est
              ipsam velit non maxime iste et quidem saepe id iusto deserunt eos
              nihil vitae et totam sapiente.
            </p>
            <br></br>
            <p>Recipe Name:</p>
            <p>Prep Time:</p>
            <p>Cook Time:</p>
            <p>Total Time: </p>
            <p>Ingredients: </p>
            <p>Directions:</p>
            <p>Created by: </p>
            <p>Other Recipes like this: </p>
          </div>
        </main>
      </main>
    </>
  );
};

export default Page;
