import Head from "next/head";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import { recipesData } from "../../queries/recipes";
import { SanityImage } from "../../components/image/SanityImage";
import { RecipeCard } from "../../components/recipeCard";

// getStaticProps
export const getStaticProps: GetStaticProps = async (context) => {
  const pageProps = await recipesData(context);

  return {
    props: {
      page: pageProps?.data || null,
    },
  };
};

export const Page = (data: InferGetStaticPropsType<typeof getStaticProps>) => {
  let recipes = data.page;
  return (
    <>
      <Head>
        <title>Recipe Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {recipes ? (
        <main>
          <div className="container bg-white mx-auto m-10 p-10 rounded overflow-hidden shadow-xl mt-4 text-center">
            <h1>Testing Recipe Collection</h1>

            <div className="flex m-10">
              <div className="grid gap-10 grid-cols-4 grid-rows-4">
                {recipes?.map((recipe: any) => {
                  return <RecipeCard recipe={recipe} post={recipe} />;
                })}
              </div>
            </div>
          </div>
        </main>
      ) : null}
    </>
  );
};

export default Page;
