import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

export default function Home() {
  // get every recipe
  return (
    <>
      <Head>
        <title>Recipe Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Testing Recipe Collection</h1>
        </div>
      </main>
    </>
  );
}
