import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // let d1 = new Date();
  // let dateTogether = new Date("12/26/2016");
  // if (typeof window !== "undefined") {
  //   if (d1.getMonth() > dateTogether.getMonth()) {
  //     alert(d1.getFullYear() - dateTogether.getFullYear());
  //   } else {
  //     alert(d1.getFullYear() - dateTogether.getFullYear() - 1);
  //   }
  // }
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          Thank you for sending us a message! We will get back to you when we
          can.
        </h1>
      </main>
    </>
  );
}
